name: Build, Test and Deploy SwCardGame

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --force

      - name: Run Tests
        run: npm run test:deploy

      - name: Build Angular App
        run: npm run build:ci

      - name: Set Git User
        run: |
          git config --global user.email "michalkozlowski936@gmail.com"
          git config --global user.name "Zombely"

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/sw-card-game/browser
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
